version: 2
jobs:
  build:
    working_directory: ~/invoicer-chapter3  # Match your local path
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Initialize Go Modules
          command: |
            go mod tidy  # Ensure dependencies are fetched
      - run:
          name: Build Application
          command: |
            go build -o bin/invoicer main.go
      - run:
          name: Run Application
          command: |
            ./bin/invoicer &
          background: true
