version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.21
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod tidy
      - run:
          name: Build project
          command: go build -o invoicer main.go
      - persist_to_workspace:
          root: .
          paths:
            - invoicer

  test:
    docker:
      - image: circleci/golang:1.21
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test ./...

  docker-build:
    docker:
      - image: circleci/golang:1.21
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t hamna/invoicer:latest .
      - persist_to_workspace:
          root: .
          paths:
            - invoicer

  docker-push:
    docker:
      - image: circleci/golang:1.21
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push hamna/invoicer:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
      - docker-push:
          requires:
            - docker-build
