version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.18  # Use latest stable Go version
    working_directory: ~/project  # Avoid GOPATH dependency

    steps:
      - checkout

      - run:
          name: Enable Go Modules
          command: |
            go env -w GO111MODULE=on

      - run:
          name: Initialize Go Modules (if missing)
          command: |
            if [ ! -f "go.mod" ]; then go mod init github.com/HamnaAhsann/invoicer-chapter3; fi
            go mod tidy

      - run:
          name: Build Application
          command: |
            go build -o invoicer main.go

      - run:
          name: Run Unit Tests
          command: |
            go test -v ./...

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t hamnaahsann/invoicer-chapter3 .

      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push hamnaahsann/invoicer-chapter3
