version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.18
    working_directory: ~/project  # Avoid GOPATH dependency

    steps:
      - checkout

      - run:
          name: Enable Go Modules
          command: |
            go env -w GO111MODULE=on

      - run:
          name: Synchronize Vendor Directory
          command: |
            go mod tidy
            go mod vendor  # This ensures dependencies are properly stored

      - run:
          name: Build Application
          command: |
            go build -o invoicer main.go

      - run:
          name: Run Unit Tests
          command: |
            go test -v ./...

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t hamnaahsann/invoicer-chapter3 .

      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push hamnaahsann/invoicer-chapter3
