version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.18  # Use an appropriate image for your language
    steps:
      - checkout
      
      # Ensure bin/invoicer is built before copying in Docker
      - run:
          name: Build Invoicer Binary
          command: |
            mkdir -p bin
            go build -o bin/invoicer cmd/invoicer/main.go  # Adjust for your project structure

      - run:
          name: Run Unit Tests
          command: go test ./...  # Runs tests (adjust as needed)

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: docker build -t myapp:latest .

      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Image to Docker Hub
          command: docker tag myapp:latest mydockerhubuser/myapp:latest && docker push mydockerhubuser/myapp:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
